stages:
  - test

default:
  image: artifactory-pub.bit9.local:5000/cookiemonster-phoenix-centos7-python36:master
  before_script:
    - curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/linux_64bit/session-manager-plugin.rpm" -o "session-manager-plugin.rpm"
    - yum install -y session-manager-plugin.rpm

test:
  only:
    refs:
      - branches
  stage: test
  tags:
    - Summoner
  script:
    - pip3 install -r requirements-dev.txt
    - black --line-length 160 --check ssmpfwd
    - tox -e py36-local,report
  except:
    - merge_requests

test-installation:
  only:
    refs:
      - branches
  stage: test
  tags:
    - Summoner
  script:
    - pip3 install -no-cache-dir -e .
    - ssmpfwd --help
    - ssmpfwd --version
  except:
    - merge_requests
    - master